name: CraftOfClansVault
main: it.itpao25.craftofclansvault.cocvault.CocVault
version: 1.1
description: Extension for CraftOfClans plugin
author: itpao25
depend: [Vault]
commands:
   cocvault:
      description: CraftOfClansVault main